/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создание отп кода */
        post: operations["OtpsController_createOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/otps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** страница с отп кодами */
        get: operations["AppController_otps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Авторизация */
        post: operations["UsersController_signin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить сессию пользователя */
        get: operations["UsersController_session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateOtpDto: {
            /** @example 89990009999 */
            phone: string;
        };
        OtpResponse: {
            /** @description Статус запроса */
            success: boolean;
            /** @description Причина ошибки */
            reason?: string;
            /**
             * @description Время запроса повторного отп кода в мс
             * @example 120000
             */
            retryDelay: number;
        };
        SignInDto: {
            /**
             * @description Номер телефона
             * @example 89990009999
             */
            phone: string;
            /**
             * @description Отп код
             * @example 345231
             */
            code: number;
        };
        User: {
            /** @description ID пользователя */
            _id: string;
            /**
             * @description Номер телефона
             * @example 89990009999
             */
            phone: string;
            /**
             * @description Имя
             * @example firstname
             */
            firstname?: string;
            /**
             * @description Отчество
             * @example middlename
             */
            middlename?: string;
            /**
             * @description Фамилия
             * @example lastname
             */
            lastname?: string;
            /**
             * @description Почта
             * @example email@gmail.com
             */
            email?: string;
            /**
             * @description Город
             * @example city
             */
            city?: string;
        };
        SignInResponse: {
            /** @description Статус запроса */
            success: boolean;
            /** @description Причина ошибки */
            reason?: string;
            /** @description Пользователь */
            user: components["schemas"]["User"];
            /** @description Пользовательский токен */
            token: string;
        };
        SessionResponse: {
            /** @description Статус запроса */
            success: boolean;
            /** @description Причина ошибки */
            reason?: string;
            /** @description Пользователь */
            user: components["schemas"]["User"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    OtpsController_createOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOtpDto"];
            };
        };
        responses: {
            /** @description create otp */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpResponse"];
                };
            };
        };
    };
    AppController_otps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful retrieval of OTPs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    UsersController_signin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInDto"];
            };
        };
        responses: {
            /** @description signin */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResponse"];
                };
            };
        };
    };
    UsersController_session: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
}
